#include "chars.h"
// TODO: evtl. näher an Xaero (aber dann nur über Reaktionszeit!)
skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/fritzkrieg_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/fritzkrieg_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/fritzkrieg_t.c"
	CHARACTERISTIC_CHAT_NAME					"Fritzkrieg"
	CHARACTERISTIC_ALERTNESS					0.3
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_TEAMPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_ENEMY_PREFERENCE				0.95
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						1.0
	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_AIM_SKILL					0.95
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.9
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.9
	CHARACTERISTIC_FIRETHROTTLE					1.0
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/fritzkrieg_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/fritzkrieg_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/fritzkrieg_t.c"
	CHARACTERISTIC_CHAT_NAME					"Fritzkrieg"
	CHARACTERISTIC_ALERTNESS					0.3
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_TEAMPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_ENEMY_PREFERENCE				0.95
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						1.0
	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_AIM_SKILL					0.95
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.9
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.9
	CHARACTERISTIC_FIRETHROTTLE					1.0
}
skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/fritzkrieg_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/fritzkrieg_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/fritzkrieg_t.c"
	CHARACTERISTIC_CHAT_NAME					"Fritzkrieg"
	CHARACTERISTIC_ALERTNESS					0.3
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_TEAMPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_ENEMY_PREFERENCE				0.95
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						1.0
	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_AIM_SKILL					0.95
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.9
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.9
	CHARACTERISTIC_FIRETHROTTLE					1.0
}
