#include "chars.h"

skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/grunt_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/grunt_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/grunt_t.c"
	CHARACTERISTIC_CHAT_NAME					"Grunt"
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_ALERTNESS					0.25
	CHARACTERISTIC_VIEW_FACTOR					0.75
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.75
	CHARACTERISTIC_CROUCHER						0.15
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8
	CHARACTERISTIC_FIRETHROTTLE					1.0
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/grunt_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/grunt_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/grunt_t.c"
	CHARACTERISTIC_CHAT_NAME					"Grunt"
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_ALERTNESS					0.25
	CHARACTERISTIC_VIEW_FACTOR					0.75
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.75
	CHARACTERISTIC_CROUCHER						0.15
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8
	CHARACTERISTIC_FIRETHROTTLE					1.0
}

skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/grunt_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/grunt_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/grunt_t.c"
	CHARACTERISTIC_CHAT_NAME					"Grunt"
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_ALERTNESS					0.25
	CHARACTERISTIC_VIEW_FACTOR					0.75
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.75
	CHARACTERISTIC_CROUCHER						0.15
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8
	CHARACTERISTIC_FIRETHROTTLE					1.0
}
