#include "chars.h"
// TODO: evtl. näher an Xaero (aber dann nur über Reaktionszeit!)
skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/klansman_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/klansman_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/klansman_t.c"
	CHARACTERISTIC_CHAT_NAME					"Klansman"
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_TEAMPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_ENEMY_PREFERENCE				0.95
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						1.0
	CHARACTERISTIC_CROUCHER						0.6
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_ATTACK_DISTANCE				120
	CHARACTERISTIC_ATTACK_RANGE					100
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_LEADER_STRATEGY				1
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/klansman_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/klansman_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/klansman_t.c"
	CHARACTERISTIC_CHAT_NAME					"Klansman"
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_TEAMPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_ENEMY_PREFERENCE				0.95
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						1.0
	CHARACTERISTIC_CROUCHER						0.6
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_ATTACK_DISTANCE				120
	CHARACTERISTIC_ATTACK_RANGE					100
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_LEADER_STRATEGY				1
}

skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/klansman_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/klansman_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/klansman_t.c"
	CHARACTERISTIC_CHAT_NAME					"Klansman"
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_TEAMPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_ENEMY_PREFERENCE				0.95
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						1.0
	CHARACTERISTIC_CROUCHER						0.6
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_ATTACK_DISTANCE				120
	CHARACTERISTIC_ATTACK_RANGE					100
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_LEADER_STRATEGY				1
}
