#include "chars.h"

skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/sarge_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/sarge_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/sarge_t.c"
	CHARACTERISTIC_CHAT_NAME					"Sarge"
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_ALERTNESS					0.35
	CHARACTERISTIC_VIEW_FACTOR					0.85
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.15
	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_AGILITY						0.45
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.85
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.85
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.9
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.85
	CHARACTERISTIC_AIM_ACCURACY					0.5
	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_FIRETHROTTLE					0.9
	CHARACTERISTIC_LEADER_STRATEGY				3
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/sarge_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/sarge_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/sarge_t.c"
	CHARACTERISTIC_CHAT_NAME					"Sarge"
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_ALERTNESS					0.35
	CHARACTERISTIC_VIEW_FACTOR					0.85
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.15
	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_AGILITY						0.45
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.85
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.85
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.9
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.85
	CHARACTERISTIC_AIM_ACCURACY					0.65
	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.9
	CHARACTERISTIC_FIRETHROTTLE					0.9
	CHARACTERISTIC_LEADER_STRATEGY				3
}

skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/sarge_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/sarge_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/sarge_t.c"
	CHARACTERISTIC_CHAT_NAME					"Sarge"
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_ALERTNESS					0.35
	CHARACTERISTIC_VIEW_FACTOR					0.85
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.15
	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_AGILITY						0.45
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.85
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.85
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.9
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.85
	CHARACTERISTIC_AIM_ACCURACY					0.7
	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.95
	CHARACTERISTIC_FIRETHROTTLE					0.9
	CHARACTERISTIC_LEADER_STRATEGY				3
}
