#include "chars.h"
// TODO:
// evtl. näher an Fritz (aber dann nur über Reaktionszeit!)
skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/visor_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/visor_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/visor_t.c"
	CHARACTERISTIC_CHAT_NAME					"Visor"
	CHARACTERISTIC_REACTIONTIME					0.1
	CHARACTERISTIC_VIEW_FACTOR					0.75
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.75
	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				1.0
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8
	CHARACTERISTIC_AIM_ACCURACY					0.75
	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.75
	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_LEADER_STRATEGY				4
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/visor_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/visor_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/visor_t.c"
	CHARACTERISTIC_CHAT_NAME					"Visor"
	CHARACTERISTIC_REACTIONTIME					0.1
	CHARACTERISTIC_VIEW_FACTOR					0.75
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.75
	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				1.0
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8
	CHARACTERISTIC_AIM_ACCURACY					0.9
	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.9
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.9
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.9
	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_LEADER_STRATEGY				4
}

skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/visor_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/visor_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/visor_t.c"
	CHARACTERISTIC_CHAT_NAME					"Visor"
	CHARACTERISTIC_REACTIONTIME					0.1
	CHARACTERISTIC_VIEW_FACTOR					0.75
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_CAMPER						0.75
	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				1.0
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8
	CHARACTERISTIC_AIM_ACCURACY					0.95
	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.95
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.95
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.95
	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_LEADER_STRATEGY				4
}
