#include "chars.h"
// TODO: richtige Waffenreihenfolge
skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaero_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaero_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xaero_t.c"
	CHARACTERISTIC_CHAT_NAME					"Xaero"
	CHARACTERISTIC_AGGRESSION					0.4
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_TEAMPRESERVATION				0.7
	CHARACTERISTIC_CROUCHER						0.0
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaero_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaero_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xaero_t.c"
	CHARACTERISTIC_CHAT_NAME					"Xaero"
	CHARACTERISTIC_AGGRESSION					0.4
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_TEAMPRESERVATION				0.7
	CHARACTERISTIC_CROUCHER						0.0
}

skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaero_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaero_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xaero_t.c"
	CHARACTERISTIC_CHAT_NAME					"Xaero"
	CHARACTERISTIC_AGGRESSION					0.4
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_TEAMPRESERVATION				0.7
	CHARACTERISTIC_CROUCHER						0.0
}
