#include "chars.h"
// TODO: richtige Waffenreihenfolge (evtl. wie Arachnotron u. Crash, also Plasmagun weit vorne!)
skill 1
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaerena_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaerena_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xaerena_t.c"
	CHARACTERISTIC_CHAT_NAME					"Xaerena"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_TEAMPRESERVATION				0.7
	CHARACTERISTIC_OBTRUSIVENESS				0.1
	CHARACTERISTIC_LEADER_STRATEGY				4
}

skill 4
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaerena_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaerena_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xaerena_t.c"
	CHARACTERISTIC_CHAT_NAME					"Xaerena"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_TEAMPRESERVATION				0.7
	CHARACTERISTIC_OBTRUSIVENESS				0.1
	CHARACTERISTIC_LEADER_STRATEGY				4
}

skill 5
{
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaerena_i.c"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaerena_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xaerena_t.c"
	CHARACTERISTIC_CHAT_NAME					"Xaerena"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_TEAMPRESERVATION				0.7
	CHARACTERISTIC_OBTRUSIVENESS				0.1
	CHARACTERISTIC_LEADER_STRATEGY				4
}
